analytics: {}
color:
  brandColors:
    - '#202215'
    - '#453F29'
    - '#E2ECF6'
    - '#A57062'
    - '#C49486'
  brandStrength: 0.756579
  lightness: 0.661184
  rhythmicContrast: 0.716283
  saturation: 0.481908
cta: {}
layout_spectrum: 0.57977
name: Eric Gerleman
opengraph: {}
purpose: {}
typography_spectrum: 0.523026
