name: Eric Gerleman
layout_spectrum: 0.57977
typography_spectrum: 0.523026
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#202215'
    - '#453F29'
    - '#E2ECF6'
    - '#A57062'
    - '#C49486'
  brandStrength: 0.756579
  lightness: 0.661184
  saturation: 0.481908
  rhythmicContrast: 0.716283
purpose: {}
title: SAG/AFTRA
author:
  name: Eric
  url: ''
  email: Gerleman
content_rating:
  adult: false
